config/routes.rb
Rails.application.routes.draw do

  resources :series
  
  namespace :admin do
    resources :series
  end 

  get 'series/title/:title', to: 'series#single', as: 'series_title'
  get 'series/title/:title' => 'series#single'

  root 'home#index'
  get 'test'    => 'test#test'
  get 'privacy' => 'test#privacy'
  get 'general' => 'test#general'
  get 'giving'  => 'giving#index'
  
  get 'pages/about' => 'pages#about'
  

end

app/models/series.rb
class Series < ActiveRecord::Base
end

app/controllers/admin/series_controller.rb
class Admin::SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]
  before_action :set_series_by_title, only: [:single]

  # GET /series
  # GET /series.json
  def index
    @series = Series.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
    @soundcloud = PNC::SermonSeries.soundcloud(@series)
  end
  
  # GET /series/title/:title
  def single
    @soundcloud = PNC::SermonSeries.soundcloud(@series)
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params_mod(series_params))

    respond_to do |format|
      if @series.save
        format.html { redirect_to admin_series_index_path, notice: 'Series was successfully created.' }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params_mod(series_params))
        format.html { redirect_to admin_series_index_path, notice: 'Series was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to admin_series_index_path, notice: 'Series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end
    
    def set_series_by_title
      @series = Series.find_by(stitle: params[:title])
    end
    
    # Create URL Safe Title
    def series_params_mod(posted)
      posted[:stitle] = PNC::SermonSeries.url_format_title(posted[:title])
      posted
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:title, :stitle, :photo, :podcast_photo, :body, :published, :width, :height, :scrolling, :frameborder, :playlist, :color, :autoplay, :hide_related, :show_comments, :show_user, :show_reposts)
    end
end

app/controllers/application_controller.rb
require 'PNC/PNC'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/giving_controller.rb
class GivingController < ApplicationController
  def index
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def about
    
  end
  
  
  
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show]
  before_action :set_series_by_title, only: [:single]

  # GET /series
  # GET /series.json
  def index
    @series = Series.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
    @soundcloud = PNC::SermonSeries.soundcloud(@series)
  end
  
  # GET /series/title/:title
  def single
    @soundcloud = PNC::SermonSeries.soundcloud(@series)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end
    
    def set_series_by_title
      @series = Series.find_by(stitle: params[:title])
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def test
    
  end
  
  def privacy
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_menu_item(loc)
    if loc == params[:controller]
      return " current-menu-item page_item current_page_item"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/admin/series/_editform.html.erb
<%= form_for(@series, url: "/admin/series/#{@series.id}") do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :stitle %><br>
    <%= f.text_field :stitle %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :podcast_photo %><br>
    <%= f.text_field :podcast_photo %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.text_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :scrolling %><br>
    <%= f.text_field :scrolling %>
  </div>
  <div class="field">
    <%= f.label :frameborder %><br>
    <%= f.text_field :frameborder %>
  </div>
  <div class="field">
    <%= f.label :playlist %><br>
    <%= f.text_field :playlist %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :autoplay %><br>
    <%= f.check_box :autoplay %>
  </div>
  <div class="field">
    <%= f.label :hide_related %><br>
    <%= f.check_box :hide_related %>
  </div>
  <div class="field">
    <%= f.label :show_comments %><br>
    <%= f.check_box :show_comments %>
  </div>
  <div class="field">
    <%= f.label :show_user %><br>
    <%= f.check_box :show_user %>
  </div>
  <div class="field">
    <%= f.label :show_reposts %><br>
    <%= f.check_box :show_reposts %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/series/_newform.html.erb
<%= form_for(@series, url: admin_series_index_path ) do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :stitle %><br>
    <%= f.text_field :stitle %>
  </div>
  <div class="field">
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </div>
  <div class="field">
    <%= f.label :podcast_photo %><br>
    <%= f.text_field :podcast_photo %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.text_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :scrolling %><br>
    <%= f.text_field :scrolling %>
  </div>
  <div class="field">
    <%= f.label :frameborder %><br>
    <%= f.text_field :frameborder %>
  </div>
  <div class="field">
    <%= f.label :playlist %><br>
    <%= f.text_field :playlist %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :autoplay %><br>
    <%= f.check_box :autoplay %>
  </div>
  <div class="field">
    <%= f.label :hide_related %><br>
    <%= f.check_box :hide_related %>
  </div>
  <div class="field">
    <%= f.label :show_comments %><br>
    <%= f.check_box :show_comments %>
  </div>
  <div class="field">
    <%= f.label :show_user %><br>
    <%= f.check_box :show_user %>
  </div>
  <div class="field">
    <%= f.label :show_reposts %><br>
    <%= f.check_box :show_reposts %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/series/edit.html.erb
<h1>Editing: <%= @series.title %></h1>

<%= render 'editform' %>

<%= link_to 'Show', admin_series_path(@series.id) %> |
<%= link_to 'Back', admin_series_index_path %>

app/views/admin/series/index.html.erb
<% if notice %>
<p data-alert id="notice" class="alert-success"><%= notice %><a class="close">&times;</a></p>
<% end %>

<% @series.each do |series| %>
<article class="series_list">
  <header>
    <img class="series_podcast_photo" src="<%= series.podcast_photo %>" />
    <h1><%= link_to series.title, series_title_path(series.stitle) %></h1>
  </header>
  <section>
    <p><%= series.body %></p>
  </section>
  <p style="clear:both; text-align:right; margin-right: 3px;">Series Controls: <%= link_to 'New', new_admin_series_path %> | 
                      <%= link_to 'Edit', edit_admin_series_path(series.id) %> | 
                      <%= link_to 'Delete', admin_series_path(series.id), data: {:method => :delete, confirm: "Are you sure?" } %> | 
                      <%= link_to 'Details', admin_series_path(series.id) %>
  </p>
</article>

<% end %>

app/views/admin/series/new.html.erb
<h1>New series</h1>

<%= render 'newform' %>

<%= link_to 'Back', series_index_path %>

app/views/admin/series/show.html.erb
<% if notice %>
<p data-alert id="notice" class="alert-success"><%= notice %><a class="close">&times;</a></p>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @series.title %>
</p>

<p>
  <strong>Sanitized Title:</strong>
  <a href="/series/title/<%= @series.stitle %>"><%= @series.stitle %></a>
</p>

<p>
  <strong>SoundCloud Player</strong>
  <%= raw @soundcloud %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @series.photo %>
</p>
<p><img src="<%= @series.photo %>" /></p>

<p>
  <strong>Podcast photo:</strong>
  <%= @series.podcast_photo %>
</p>
<p><img src="<%= @series.podcast_photo %>" /></p>

<p>
  <strong>Body:</strong>
  <%= @series.body %>
</p>

<p>
  <strong>Published:</strong>
  <%= @series.published %>
</p>

<p>
  <strong>Width:</strong>
  <%= @series.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @series.height %>
</p>

<p>
  <strong>Scrolling:</strong>
  <%= @series.scrolling %>
</p>

<p>
  <strong>Frameborder:</strong>
  <%= @series.frameborder %>
</p>

<p>
  <strong>Playlist:</strong>
  <%= @series.playlist %>
</p>

<p>
  <strong>Color:</strong>
  <%= @series.color %>
</p>

<p>
  <strong>Autoplay:</strong>
  <%= @series.autoplay %>
</p>

<p>
  <strong>Hide related:</strong>
  <%= @series.hide_related %>
</p>

<p>
  <strong>Show comments:</strong>
  <%= @series.show_comments %>
</p>

<p>
  <strong>Show user:</strong>
  <%= @series.show_user %>
</p>

<p>
  <strong>Show reposts:</strong>
  <%= @series.show_reposts %>
</p>

<%= link_to 'Edit', edit_admin_series_path(@series) %> | 
<%= link_to 'Delete', admin_series_path(@series.id), data: {:method => :delete, confirm: "Are you sure?" } %> | 
<%= link_to 'Back', admin_series_index_path %>

app/views/admin/series/single.html.erb
<article class="series_single row">
  <header class="medium-12 columns">
    <img class="series_photo" src="<%= @series.photo %>" />
    <h1><%= @series.title %></h1>
    <p><%= raw @series.body %></p>
  </header>
  <section class="medium-12 columns">
    <div class="medium-4 columns">
      Article Sidebar
    </div>
    <div class="medium-8 columns">
      <%= raw @soundcloud %>
    </div>
  </section>
</article>

app/views/layouts/_footer.html.erb
      <footer class="site-footer" role="contentinfo" itemscope="itemscope" itemtype="http://schema.org/WPFooter">
        <div class="wrap">
          <div id="gwfoot-footer-one-area" class="gwfoot-footer-one-one-third">
            <div id="text-7" class="gwfoot-footer-one widget-area widget_text">
              <div class="textwidget">
                <!-- Begin area to paste into Wordpress Widget -->
                <div style="display:none;" class="row">
                  <div class="medium-8 columns" style="background: white;">
                    Eight columns
                  </div>
                  <div class="medium-4 columns" style="background: blue;">
                    Four columns
                  </div>
                </div>
                <!-- End area to paste into Wordpress Widget -->
              </div>
            </div>
          </div><!-- end #gwfoot-footer-one-area -->
          <div id="gwfoot-footer-two-area" class="gwfoot-footer-two-two-thirds">
            <div id="text-8" class="gwfoot-footer-two widget-area widget_text">
              <div class="textwidget">
                <!-- Begin area to paste into Wordpress Widget -->
                <div style="display:none;" class="row">
                  <div class="medium-8 columns" style="background: white;">
                    Eight columns
                  </div>
                  <div class="medium-4 columns" style="background: blue;">
                    Four columns
                  </div>
                </div>
                <!-- End area to paste into Wordpress Widget -->
              </div>
            </div>
          </div><!-- end #gwfoot-footer-two-area -->
        </div>
      </footer>

app/views/layouts/_frontpage.html.erb
<div class="site-inner">
  <div class="content-sidebar-wrap">
    <main class="content" role="main" itemprop="mainContentOfPage">
      <div class="home-odd home-section-1 widget-area">
        <div class="wrap">
          <section id="text-2" class="widget widget_text">
            <div class="widget-wrap">
              <h4 class="widget-title widgettitle">Welcome!</h4>
              <div class="textwidget">
                <p>
                  This is a bit of sample text.
                </p>
                <p>
                  <a class="button-p" href="/test">Test Page</a>
                </p>
              </div>
            </div>
          </section>
        </div>
      </div>
      <div class="home-even home-section-2 widget-area">
        <div class="wrap">
          <section id="text-3" class="widget widget_text">
            <div class="widget-wrap">
              <h4 class="widget-title widgettitle">Sermons</h4>
              <div class="textwidget">
                <p>
                  <iframe width="100%" height="300" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/pointe-north&amp;color=77B800&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>
                </p>
              </div>
            </div>
          </section>
        </div>
      </div>
      <div class="home-odd home-section-3 widget-area">
        <div class="wrap">
          <section id="text-5" class="widget widget_text">
            <div class="widget-wrap">
              <h4 class="widget-title widgettitle">What&#8217;s Happening Here</h4>
              <div class="textwidget"></div>
            </div>
          </section>
        </div>
      </div>
    </main>
  </div>
</div>

app/views/layouts/_gwfoot.html.erb
      <div id="gwfoot-footer-disclaimer-area">
        <div class="gwfoot-footer-disclaimer-content">
          <div id="text-6" class="gwfoot-footer-disclaimer widget-area widget_text">
            <div class="textwidget">
              <!-- Begin area to paste into Wordpress Widget -->
              <div class="row">
                <div class="medium-8 columns">
                  <ul>
                    <li>&#x000A9;&nbsp;2014 Pointe North Church - All Rights Reserved</li>
                    <li>110 Bilo Drive, Moncks Corner, SC, 29461</li>
                    <li>Telephone: <a href="tel:843-761-6196">843-761-6196</a></li>
                    <li>Email: <a href="mailto:pnccinfo@pointenorth.org">pnccinfo@pointenorth.org</a></li>
                  </ul>
                  <p>
                    <a href="https://pnccchssc.infellowship.com/UserLogin/Index?ReturnUrl=%2fonlinegiving%2fgivenow%2fstep1" target="_blank">Online Giving</a> |
                    <a href="http://www.bing.com/maps/#Y3A9MzMuMTg4NDgwfi03OS45OTU5NzkmbHZsPTE2JnN0eT1yJnJ0cD1hZHIufnBvcy4zMy4xODg3NDdfLTc5Ljk5Njk3OV8xMTAlMjBCaWxvJTIwRHIlMkMlMjBNb25ja3MlMjBDb3JuZXIlMkMlMjBTQyUyMDI5NDYxX19fZV8mbW9kZT1EJnJ0b3A9MH4wfjB+" target="_blank">Directions</a> |
                    <a href="#prayer_requests">Prayer Requests</a> |
                    <a href="/privacy">Privacy Policy</a>
                  </p>
                </div>
                <div class="medium-4 columns">
                  <!-- Image URLS need to be /wp-content/themes/pnc-parallax/images/{IMAGE_NAME} -->
                  <p>
                    <a href="http://www.bible.com/app" target="_blank">
                      <img id="youversion" src="/assets/color_logo.png" />
                      <img id="bible" src="/assets/Bible-app-icon-english-144x144.png" />
                    </a>
                  </p>
                  <!-- Image URLS need to be /wp-content/themes/pnc-parallax/images/social/{IMAGE_NAME} -->
                  <p style="padding-top: 10px;">
                    <a href="[site_url]/feed"><img class="social" id="rss" src="/assets/social/rss-128.png" /></a>
                    <a href="mailto:pnccinfo@pointenorth.org" target="_blank"><img class="social" id="email" src="/assets/social/email-128.png" /></a>
                    <a href="https://www.facebook.com/PointeNorth" target="_blank"><img class="social" id="facebook" src="/assets/social/facebook-128.png" /></a>
                    <a href="https://twitter.com/pncc_sc" target="_blank"><img class="social" id="twitter" src="/assets/social/twitter-128.png" /></a>
                    <a href="http://instagram.com/pncc_sc" target="_blank"><img class="social" id="instagram" src="/assets/social/instagram-128.png" /></a>
                    <img style="cursor: pointer;" id="paypal_footer" class="social" id="paypal" src="/assets/social/paypal-128.png" onclick="document.forms['paypal_form'].submit();" />
                    <form id="paypal_form" action="https://www.paypal.com/cgi-bin/webscr" method="post">
                        <input name="cmd" value="_s-xclick" type="hidden">
                        <input name="hosted_button_id" value="P8SXZVLAKNRQW" type="hidden">
                    </form>
                  </p>
                </div>
              </div>
              <!-- End area to paste into Wordpress Widget -->
            </div>
          </div>
        </div><!-- end .gwfoot-footer-disclaimer-content -->
      </div><!-- end #gwfoot-footer-disclaimer-area -->

app/views/layouts/_header.html.erb
      <header class="site-header" role="banner" itemscope="itemscope" itemtype="http://schema.org/WPHeader">
        <div class="wrap">
          <div class="title-area">
            <h1 class="site-title" itemprop="headline"><a href="http://pnc.skar-lett.com/">PNC Test</a></h1>
            <h2 class="site-description" itemprop="description">Bringing People Closer to Jesus</h2>
          </div>
          <aside class="widget-area header-widget-area">
            <section id="nav_menu-2" class="widget widget_nav_menu">
              <div class="widget-wrap">
                <nav class="nav-header" role="navigation" itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement">
                  <ul id="menu-main-menu" class="menu genesis-nav-menu">
                    <li id="menu-item-home" class="menu-item menu-item-type-post_type menu-item-object-page<%= active_menu_item('home') %>"><a href="/">Home</a></li>
                    <li id="menu-item-test" class="menu-item menu-item-type-post_type menu-item-object-page<%= active_menu_item('test') %>"><a href="/test">Test Page</a>
                      <ul class="sub-menu">
                        <li id="menu-item-89" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-89"><a href="http://www.pointenorth.org">Test Link 1</a></li>
                        <li id="menu-item-90" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-90"><a href="http://www.pointenorth.org">Test Link 2</a></li>
                      </ul>
                    </li>
                    <li id="menu-item-online-giving" class="menu-item menu-item-type-post_type menu-item-object-page<%= active_menu_item('giving') %>"><a href="/giving">Onine Giving</a></li>
                    <li id="menu-item-sermon" class="menu-item menu-item-type-post_type menu-item-object-page<%= active_menu_item('series') %>"><a href="/series">Sermons</a></li>
                    <li id="menu-item-test" class="menu-item menu-item-type-post_type menu-item-object-page<%= active_menu_item('volunteer') %>"><a href="/volunteer">Get Involved</a></li>
                  </ul>
                </nav>
              </div>
            </section>
          </aside>
        </div>
      </header>

app/views/layouts/_pre_footer.html.erb
      <div class="footer-widgets">
        <div class="wrap">
          <div class="footer-widgets-1 widget-area">
            <section id="text-6" class="widget widget_text">
              <div class="widget-wrap">
                <h4 class="widget-title widgettitle">Sample Footer Header</h4>
                <div class="textwidget">
                  <p>Sample Footer Text.</p>
                </div>
              </div>
            </section>
            <section id="text-7" class="widget widget_text">
              <div class="widget-wrap">
                <h4 class="widget-title widgettitle">Sample Header 2</h4>
                <div class="textwidget">
                  <p>
                    Sample header 2 text.
                  </p>
                </div>
              </div>
            </section>
          </div>
        </div>
      </div>

app/views/layouts/_site_inner.html.erb
      <div class="site-inner">
        <div class="content-sidebar-wrap">
          <main class="content" role="main" itemprop="mainContentOfPage">

            <% if params[:controller] == "home" %>
            
            <div class="home-odd home-section-1 widget-area">
              <div class="wrap">
                <section id="text-2" class="widget widget_text">
                  <div class="widget-wrap">
                    <h4 class="widget-title widgettitle">Welcome!</h4>
                    <div class="textwidget">
                      <p>
                        This is a bit of sample text.
                      </p>
                      <p>
                        <a class="button-p" href="/test">Test Page</a>
                      </p>
                    </div>
                  </div>
                </section>
              </div>
            </div>
            <div class="home-even home-section-2 widget-area">
              <div class="wrap">
                <section id="text-3" class="widget widget_text">
                  <div class="widget-wrap">
                    <h4 class="widget-title widgettitle">Sermons</h4>
                    <div class="textwidget">
                      <p>
                        <iframe width="100%" height="300" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/pointe-north&amp;color=77B800&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false"></iframe>
                      </p>
                    </div>
                  </div>
                </section>
              </div>
            </div>
            <div class="home-odd home-section-3 widget-area">
              <div class="wrap">
                <section id="text-5" class="widget widget_text">
                  <div class="widget-wrap">
                    <h4 class="widget-title widgettitle">What&#8217;s Happening Here</h4>
                    <div class="textwidget"></div>
                  </div>
                </section>
              </div>
            </div>            
            <script type="text/javascript" src="/assets/parallax.js"></script>
            
            <% else %>
            
            <div class="row">
            	<div class="medium-12 columns">
		            <article class="post-20 page type-page status-publish entry" itemscope="itemscope" itemtype="http://schema.org/CreativeWork">
		              <header class="entry-header" style="display:none;">
		                <h1 class="entry-title" itemprop="headline"><%= params[:action].titleize %></h1> 
		              </header>
		              
		              <%= yield %>
		              
		            </article>		
            	</div>
            </div>
            
            <% end %>

          </main>
        </div>
      </div>

app/views/layouts/elements/_paypal_form.html.erb
<img style="cursor: pointer;" id="paypal_footer" class="social" id="twitter" src="/assets/social/paypal-128.png" onclick="document.forms['paypal_form'].submit();" />
<form id="paypal_form" action="https://www.paypal.com/cgi-bin/webscr" method="post">
    <input name="cmd" value="_s-xclick" type="hidden">
    <input name="hosted_button_id" value="P8SXZVLAKNRQW" type="hidden">
</form>

app/views/series/index.html.erb
<% @series.each do |series| %>
<article class="series_list">
  <header>
    <img class="series_podcast_photo" src="<%= series.podcast_photo %>" />
    <h2><%= link_to series.title, series_title_path(series.stitle) %></h2>
  </header>
  <section>
    <p><%= series.body %></p>
  </section>
  <p style="clear:both;">&nbsp;</p>
</article>
<% end %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @series.title %>
</p>

<p>
  <strong>Stitle:</strong>
  <a href="/series/title/<%= @series.stitle %>"><%= @series.stitle %></a>
</p>

<p>
  <strong>Photo:</strong>
  <img src="<%= @series.photo %>" />
  <%= @series.photo %>
</p>

<p>
  <strong>Podcast photo:</strong>
  <img src="<%= @series.podcast_photo %>" />
  <%= @series.podcast_photo %>
</p>

<p>
  <strong>Body:</strong>
  <%= @series.body %>
</p>

<p>
  <strong>Published:</strong>
  <%= @series.published %>
</p>

<p>
  <strong>Width:</strong>
  <%= @series.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @series.height %>
</p>

<p>
  <strong>Scrolling:</strong>
  <%= @series.scrolling %>
</p>

<p>
  <strong>Frameborder:</strong>
  <%= @series.frameborder %>
</p>

<p>
  <strong>Playlist:</strong>
  <%= @series.playlist %>
</p>

<p>
  <strong>Color:</strong>
  <%= @series.color %>
</p>

<p>
  <strong>Autoplay:</strong>
  <%= @series.autoplay %>
</p>

<p>
  <strong>Hide related:</strong>
  <%= @series.hide_related %>
</p>

<p>
  <strong>Show comments:</strong>
  <%= @series.show_comments %>
</p>

<p>
  <strong>Show user:</strong>
  <%= @series.show_user %>
</p>

<p>
  <strong>Show reposts:</strong>
  <%= @series.show_reposts %>
</p>

<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>

<%= raw @soundcloud %>